# array = "Rosalind problems"
# print array[::-1]

sequence = "GCTTAAGGAAACCAACGCTGTCTGAGCTCAGCCACTATATGCACAATAGTGGTTATAGTATCATCCTGTGATTTCTAGTCATGCATCATTCACACGTCAGCCCCTCGACCTACTGGAACTGTGTGCAACAGGGCCACGGTTCAGTGCTCGGTTCCATCCAGATTAGAAAGTAGGTCATGAACAAGCAGTTTATTTCAAACCAATCGCGCACATCAAAGGCTCAGTCAGGCGTTTGGTGAAAGGCATGTCTTAGATAGTTTTTATAGAATCATGTTCTATTTCATTAGTCAACTCATTGAGCTTATATTAAGATGTGCCGATTGGGAGAATTTCCACCTCTCAGATAAATTAATCTCCGCAGCTGATTTTCGCGACGGCCGCAGGTGTGTTTTCCCGATCTGGGTCGTCTACGATAATGAAGCGAATTGCCCTGTAGGTGGAGTCGAACTAAGTCTACCTCAGATAAAACGTACGCCCTGAACCCATCAGCCGACTCGTGAACACTTAAGTACACATAACGCCTCTGAACTTGGTCAATCTAATCTCCCTACATCTACCGACTCTCGCCTAAATGCGTACGGTTCGCGCACCGGAGAGACAGGGCTACATGGACACCAGAAGAGAGGAAAGAAACAGTCTTCGTCTTGAAATAACTCAGAAGCTCTGTTTTGGATCTATTATCTTTGCTAGCGCCCAGGATACAGGGTAATACAAGTGCCCCCGTGTCCACATATAGGAAGGCCGTAAATGCAAGACAAAATAATTCACACGAAGCTGACGTTGCGGTTGTATATCTTTTCCCGTAAACACTGAGGCGAGCACCAGTGGGACCCTCAATCGCTCAATGATGTATACAGATTGACGCCAGAAAGCGATCTGCCGTGGGTACGAGGGTGGATTCACATAGGATATCCAGAGCCTCATGAATTTACTGCTGTACCTCGGTATTCGTTCCCATCAACTTACACGGAGGCTTA"
result =""
# reversed_sequence=""

for base in sequence:
    if base=="A":
        result+="T"
    elif base=="T":
        result+="A"
    elif base=="C":
        result+="G"
    elif base=="G":
        result+="C"

print result[::-1]
