sequence="CGACAACACAAACTGTACCAGGGACGGATTCAAGTACTGCGTCTTAAGTCCGCGACAGAGTGATTATGCATCAACGAGTAAGGAATGATTCTCTCGATCAAGATTGGGCAGGCCACCTCTACCACGGTACTGCGTCGGAGAAGAAGTGACTGAGTTCATCGGCCGAAATTATGGGAGTTTTGGCTCGGGCCTTAGCCCGATTAATACGGGGGCCGTTTTTTGTCTCGATTAGGGAAGTACCTCTGTTGCTCTCCCATTCCAATCTCAGAATCCCCCTTTTTGATCGCGTGACTCACGTTTCAGCACGATTTGTGTGAGTCCACTATTTCGTTACTCGAACAAGCTTGTCTGAGAACATGGCATAGGTGGAGACCTGTATATGAAGTATTGAGGCAGTAGTGGTTCTAGCGGGGCATGCCTATGCGGAATCTTTGTTGAAGGATGCGAATAAGCCAACATATCTCTGAAAATTAACAGACGAAAGGCAGTTCCCCGCTCCCATTAGCAAGACCGATGCCTTGTTCTCGAGTGACTGAGCCCAAACGTTGTCTTGAGACTTTCGCGCTCAGGGCGTCTCAATATTCAGTCCCTCCGATTTACCGAAGCCAAGTCGCTCCCCCATTCTACGAACAGGTCAGCCTGTAGAGGGATGCCGGACTGAGCTCCACCCAGCAAATCATTAACACTCCGTGCCAAATGGTGAATTTCGTCCTTTTTGCTTGCCTTTCTGAGTACTTACCGACCCGATTCTACAGAACGGTATCACGGGAAATCCAGCCATTTGCCCGTTAGGGATCTGCTCGGGCAGAACATTAGGGCAGTCTCGTTTGAATTCACCTGTGCTCC"
A_count=0
G_count=0
C_count=0
T_count=0

for base in sequence:
    if base == "A":
        A_count=A_count+1
    elif base == "G":
        G_count=G_count+1
    elif base=="C":
        C_count=C_count+1
    elif base=="T":
        T_count=T_count+1

print "{0} {1} {2} {3}".format(A_count, C_count, G_count, T_count)
